#
# Website's configuration file.
#

name: Sarah Chen
description: I'm Sarah Chen.  Analytic expert in banking and insurance. 
avatar: /images/gogs.jpg
subheading: Analytics for financial risk management and investment
image: /images/icons/logo.png

footer-links:
  # email: sarahchen@gmail.com
  github: PythonRSAS
  linkedin: sarah-chen-276a1617
  # twitter: sarahchen
  # quora: sarahchen
  # stackoverflow:
  # youtube:

google_analytics: UA-148562161-1
url: "http://pythonrsas.com/"
baseurl: ""

permalink: /:title/
version: v1.0.0
kramdown:
  input: GFM
  # syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true
    # css_class: 'highlight'
    # span:
    #   line_numbers: false
    # block:
    #   line_numbers: true
    #   start_line: 1

sass:
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

excerpt_separator: <!--more-->

# specifies how many items should be displayed per page in the blog
paginate: 6
paginate_path: "/blog/page:num/"
recent_post_limit: 4